class CreateIndexes < ActiveRecord::Migration
  def self.up
    add_index :votes, [:statement_id, :statement_type]
    add_index :votes, [:user_id]
    add_index :memberships, [:group_id]
    add_index :memberships, [:user_id]
    add_index :groups, [:user_id]
    add_index :groups, [:founder_id]
    add_index :questions, [:user_id]
    add_index :questions, [:supervision_id]
    add_index :rules, [:group_id]
    add_index :topics, [:supervision_id]
    add_index :topics, [:user_id]
    add_index :solutions, [:supervision_id]
    add_index :solutions, [:user_id]
    add_index :feedbacks, [:supervision_id]
    add_index :feedbacks, [:user_id]
    add_index :ideas, [:supervision_id]
    add_index :ideas, [:user_id]
    add_index :chat_rooms, [:group_id]
    add_index :chat_rooms, [:leader_id]
    add_index :chat_rooms, [:problem_owner_id]
    add_index :chat_rooms, [:current_rule_id]
    add_index :chat_rooms, [:supervision_id]
    add_index :chat_messages, [:user_id]
    add_index :chat_messages, [:chat_room_id]
    add_index :supervisions, [:group_id]
    add_index :supervisions, [:topic_id]
    add_index :slugs, [:sluggable_id, :sluggable_type]
    add_index :answers, [:question_id]
    add_index :answers, [:user_id]
  end

  def self.down
    remove_index :votes, :column => [:statement_id, :statement_type]
    remove_index :votes, :column => [:user_id]
    remove_index :memberships, :column => [:group_id]
    remove_index :memberships, :column => [:user_id]
    remove_index :groups, :column => [:user_id]
    remove_index :groups, :column => [:founder_id]
    remove_index :questions, :column => [:user_id]
    remove_index :questions, :column => [:supervision_id]
    remove_index :rules, :column => [:group_id]
    remove_index :topics, :column => [:supervision_id]
    remove_index :topics, :column => [:user_id]
    remove_index :solutions, :column => [:supervision_id]
    remove_index :solutions, :column => [:user_id]
    remove_index :feedbacks, :column => [:supervision_id]
    remove_index :feedbacks, :column => [:user_id]
    remove_index :ideas, :column => [:supervision_id]
    remove_index :ideas, :column => [:user_id]
    remove_index :chat_rooms, :column => [:group_id]
    remove_index :chat_rooms, :column => [:leader_id]
    remove_index :chat_rooms, :column => [:problem_owner_id]
    remove_index :chat_rooms, :column => [:current_rule_id]
    remove_index :chat_rooms, :column => [:supervision_id]
    remove_index :chat_messages, :column => [:user_id]
    remove_index :chat_messages, :column => [:chat_room_id]
    remove_index :supervisions, :column => [:group_id]
    remove_index :supervisions, :column => [:topic_id]
    remove_index :slugs, :column => [:sluggable_id, :sluggable_type]
    remove_index :answers, :column => [:question_id]
    remove_index :answers, :column => [:user_id]
  end
end
